// FirePlus.ts
import { FirebaseApp, FirebaseOptions, initializeApp } from "firebase/app";
import {
  addDoc,
  collection,
  deleteDoc,
  doc,
  Firestore,
  getDoc,
  getDocs,
  getFirestore,
  query,
  QueryConstraint,
  updateDoc,
  where,
  DocumentData,
  DocumentReference,
  CollectionReference,
  limit,
} from "firebase/firestore";
import helpers from "@/utils/helpers";

/**
 * Base class for all Firestore models in FirePlus.
 * Provides CRUD operations and utility methods for Firestore documents.
 *
 * @example
 * ```typescript
 * @Schema()
 * class User {
 *   name: string;
 *   email: string;
 *
 *   // Constructor is automatically generated by the @Schema decorator
 * }
 * ```
 */
class FirePlus {
  /** Singleton instance of FirePlus */
  private static instance: FirePlus;
  /** Firebase app instance */
  private app!: FirebaseApp;
  /** Firestore database instance */
  private _db!: Firestore;
  /** Document ID in Firestore */
  public id?: string;
  /** Document creation timestamp */
  public createdAt?: Date;
  /** Document last update timestamp */
  public updatedAt?: Date;

  /**
   * Protected constructor to allow inheritance while still enforcing singleton pattern
   * for the base class
   * @param config Optional Firebase configuration or existing Firebase app
   */
  protected constructor(config?: FirebaseOptions | FirebaseApp) {
    this.id = undefined;
    this.createdAt = undefined;
    this.updatedAt = undefined;

    if (!FirePlus.instance) {
      FirePlus.instance = this;

      if (!config) {
        // If no config is provided, use default config
        console.warn(
          "FirePlus initialized without configuration. Make sure to set up Firebase properly."
        );
        return;
      }

      if ("options" in config) {
        // If config is a FirebaseApp instance
        this.app = config;
      } else {
        // If config is FirebaseOptions
        this.app = initializeApp(config);
      }

      this._db = getFirestore(this.app);
    } else {
      throw new Error(
        "FirePlus is a singleton class. Use FirePlus.init() instead."
      );
    }
  }

  /**
   * Initialize FirePlus with Firebase configuration
   * @param config Firebase configuration or existing Firebase app (optional)
   * @returns FirePlus instance
   */
  public static init(config?: FirebaseOptions | FirebaseApp): FirePlus {
    if (!FirePlus.instance) {
      FirePlus.instance = new FirePlus(config);
    }
    return FirePlus.instance;
  }

  /**
   * Check if FirePlus is initialized
   * @returns boolean indicating if FirePlus is initialized
   */
  public static isInitialized(): boolean {
    return !!FirePlus.instance && !!FirePlus.instance._db;
  }

  /**
   * Validate that FirePlus is initialized
   * @throws Error if FirePlus is not initialized
   */
  private static validateInitialization(): void {
    if (!FirePlus.isInitialized()) {
      throw new Error("FirePlus not initialized. Call FirePlus.init() first.");
    }
  }

  /**
   * Get the Firestore database instance
   * @returns Firestore instance
   * @throws Error if FirePlus is not initialized
   */
  public get db(): Firestore {
    FirePlus.validateInitialization();
    return this._db;
  }

  /**
   * Get the collection reference for the current model
   * @returns CollectionReference
   * @throws Error if FirePlus is not initialized
   */
  public getCollectionRef(): CollectionReference {
    FirePlus.validateInitialization();
    return collection(this.db, this.getCollectionName());
  }

  /**
   * Get the document reference for the current model
   * @param id Document ID (optional)
   * @returns DocumentReference
   * @throws Error if FirePlus is not initialized or document ID is missing
   */
  public getDocRef(id?: string): DocumentReference {
    FirePlus.validateInitialization();
    const docId = id || this.id;
    if (!docId) {
      throw new Error("Document ID is required");
    }
    return doc(this.db, this.getCollectionName(), docId);
  }

  /**
   * Get the collection name for the current model
   * @returns Collection name
   */
  public getCollectionName(): string {
    return helpers.pluralize((this.constructor as Function).name.toLowerCase());
  }

  /**
   * Get all primitive properties of the current instance
   * @returns DocumentData object with primitive properties
   */
  protected getPrimitiveProps(): DocumentData {
    const props: DocumentData = {};

    for (const key in this) {
      // Skip methods and non-primitive properties
      if (
        typeof this[key as keyof this] !== "function" &&
        !(this[key as keyof this] instanceof Date) &&
        !(this[key as keyof this] instanceof DocumentReference)
      ) {
        props[key] = this[key as keyof this];
      }
    }

    return props;
  }

  /**
   * Save the current document to Firestore
   * Creates a new document if id is not set, otherwise updates the existing document
   *
   * @example
   * ```typescript
   * const user = new User({ name: "John", email: "john@example.com" });
   * const id = await user.save();
   * console.log(`User saved with ID: ${id}`);
   * ```
   *
   * @returns Promise resolving to the document ID or null if save failed
   * @throws Error if FirePlus is not initialized
   */
  async save(): Promise<string | null> {
    FirePlus.validateInitialization();
    try {
      const data = this.getPrimitiveProps();

      // Set timestamps
      if (!this.id) {
        // New document
        data.createdAt = new Date();
        data.updatedAt = new Date();

        const docRef = await addDoc(this.getCollectionRef(), data);
        this.id = docRef.id;
        return docRef.id;
      } else {
        // Existing document
        data.updatedAt = new Date();

        await updateDoc(this.getDocRef(), data);
        return this.id;
      }
    } catch (error) {
      console.error("Error saving document:", error);
      return null;
    }
  }

  /**
   * Update the current document in Firestore
   *
   * @example
   * ```typescript
   * const user = new User({ id: "existing-id", name: "John" });
   * user.name = "Jane";
   * const success = await user.update();
   * ```
   *
   * @returns Promise resolving to true if update was successful, false otherwise
   * @throws Error if FirePlus is not initialized
   */
  async update(): Promise<boolean> {
    FirePlus.validateInitialization();
    try {
      if (!this.id) {
        throw new Error("Cannot update document without ID");
      }

      const data = this.getPrimitiveProps();
      data.updatedAt = new Date();

      await updateDoc(this.getDocRef(), data);
      return true;
    } catch (error) {
      console.error("Error updating document:", error);
      return false;
    }
  }

  /**
   * Delete the current document from Firestore
   *
   * @example
   * ```typescript
   * const user = new User({ id: "existing-id" });
   * const success = await user.delete();
   * ```
   *
   * @returns Promise resolving to true if deletion was successful, false otherwise
   * @throws Error if FirePlus is not initialized
   */
  async delete(): Promise<boolean> {
    FirePlus.validateInitialization();
    try {
      if (!this.id) {
        throw new Error("Cannot delete document without ID");
      }

      await deleteDoc(this.getDocRef());
      return true;
    } catch (error) {
      console.error("Error deleting document:", error);
      return false;
    }
  }

  /**
   * Find a document by ID
   *
   * @example
   * ```typescript
   * // Using automatic type inference
   * const foundUser = await User.findById("existing-id");
   * if (foundUser) {
   *   console.log(`Found user: ${foundUser.name}`);
   * }
   *
   * // With explicit type (not needed anymore)
   * // const foundUser = await User.findById<User>("existing-id");
   * ```
   *
   * @param id Document ID
   * @returns Promise resolving to the found document or null
   * @throws Error if FirePlus is not initialized
   */
  static async findById(id: string): Promise<any | null> {
    FirePlus.validateInitialization();
    try {
      const instance = new (this as any)();
      const docRef = instance.getDocRef(id);
      const docSnap = await getDoc(docRef);

      if (docSnap.exists()) {
        const data = docSnap.data();
        const result = new (this as any)(data);
        result.id = docSnap.id;
        return result;
      }

      return null;
    } catch (error) {
      console.error("Error finding document by ID:", error);
      return null;
    }
  }

  /**
   * Find all documents in the collection
   *
   * @example
   * ```typescript
   * // Using automatic type inference
   * const users = await User.findAll();
   * console.log(`Found ${users.length} users`);
   *
   * // With explicit type (not needed anymore)
   * // const users = await User.findAll<User>();
   * ```
   *
   * @returns Promise resolving to an array of documents
   * @throws Error if FirePlus is not initialized
   */
  static async findAll(): Promise<any[]> {
    FirePlus.validateInitialization();
    try {
      const instance = new (this as any)();
      const querySnapshot = await getDocs(instance.getCollectionRef());

      return querySnapshot.docs.map((doc) => {
        const data = doc.data();
        const result = new (this as any)(data);
        result.id = doc.id;
        return result;
      });
    } catch (error) {
      console.error("Error finding all documents:", error);
      return [];
    }
  }

  /**
   * Find documents by a specific field value
   *
   * @example
   * ```typescript
   * // Using automatic type inference
   * const users = await User.findByField("name", "John");
   * console.log(`Found ${users.length} users named John`);
   *
   * // With explicit type (not needed anymore)
   * // const users = await User.findByField<User>("name", "John");
   * ```
   *
   * @param field Field name
   * @param value Field value
   * @returns Promise resolving to an array of documents
   * @throws Error if FirePlus is not initialized
   */
  static async findByField(field: string, value: any): Promise<any[]> {
    FirePlus.validateInitialization();
    try {
      const instance = new (this as any)();
      const q = query(instance.getCollectionRef(), where(field, "==", value));

      const querySnapshot = await getDocs(q);

      return querySnapshot.docs.map((doc) => {
        const data = doc.data();
        const result = new (this as any)(data);
        result.id = doc.id;
        return result;
      });
    } catch (error) {
      console.error(`Error finding documents by field ${field}:`, error);
      return [];
    }
  }

  /**
   * Find documents using Firestore query constraints
   *
   * @example
   * ```typescript
   * // Using automatic type inference
   * const users = await User.findWhere([
   *   where("age", ">=", 18),
   *   where("city", "==", "New York")
   * ]);
   * console.log(`Found ${users.length} users matching criteria`);
   *
   * // With explicit type (not needed anymore)
   * // const users = await User.findWhere<User>([
   * //   where("age", ">=", 18),
   * //   where("city", "==", "New York")
   * // ]);
   * ```
   *
   * @param constraints Array of Firestore query constraints
   * @returns Promise resolving to an array of documents
   * @throws Error if FirePlus is not initialized
   */
  static async findWhere(constraints: QueryConstraint[]): Promise<any[]> {
    FirePlus.validateInitialization();
    try {
      const instance = new (this as any)();
      const q = query(instance.getCollectionRef(), ...constraints);

      const querySnapshot = await getDocs(q);

      return querySnapshot.docs.map((doc) => {
        const data = doc.data();
        const result = new (this as any)(data);
        result.id = doc.id;
        return result;
      });
    } catch (error) {
      console.error("Error finding documents with constraints:", error);
      return [];
    }
  }

  /**
   * Find the first document matching the query constraints
   *
   * @example
   * ```typescript
   * // Using automatic type inference
   * const user = await User.findOne([
   *   where("age", ">=", 18),
   *   where("city", "==", "New York")
   * ]);
   * if (user) {
   *   console.log(`Found user: ${user.name}`);
   * }
   *
   * // With explicit type (not needed anymore)
   * // const user = await User.findOne<User>([
   * //   where("age", ">=", 18),
   * //   where("city", "==", "New York")
   * // ]);
   * ```
   *
   * @param constraints Array of Firestore query constraints
   * @returns Promise resolving to the first matching document or null
   * @throws Error if FirePlus is not initialized
   */
  static async findOne(constraints: QueryConstraint[]): Promise<any | null> {
    FirePlus.validateInitialization();
    try {
      const instance = new (this as any)();
      const q = query(instance.getCollectionRef(), ...constraints, limit(1));

      const querySnapshot = await getDocs(q);

      if (querySnapshot.empty) {
        return null;
      }

      const doc = querySnapshot.docs[0];
      const data = doc.data();
      const result = new (this as any)(data);
      result.id = doc.id;
      return result;
    } catch (error) {
      console.error("Error finding one document:", error);
      return null;
    }
  }

  /**
   * Find the first document matching a specific field value
   *
   * @example
   * ```typescript
   * // Using automatic type inference
   * const user = await User.findOneByField("email", "john@example.com");
   * if (user) {
   *   console.log(`Found user: ${user.name}`);
   * }
   *
   * // With explicit type (not needed anymore)
   * // const user = await User.findOneByField<User>("email", "john@example.com");
   * ```
   *
   * @param field Field name
   * @param value Field value
   * @returns Promise resolving to the first matching document or null
   * @throws Error if FirePlus is not initialized
   */
  static async findOneByField(field: string, value: any): Promise<any | null> {
    FirePlus.validateInitialization();
    return this.findOne([where(field, "==", value)]);
  }

  /**
   * Check if a document exists by ID
   *
   * @example
   * ```typescript
   * const exists = await User.exists("existing-id");
   * if (exists) {
   *   console.log("Document exists");
   * }
   * ```
   *
   * @param id Document ID
   * @returns Promise resolving to true if document exists, false otherwise
   * @throws Error if FirePlus is not initialized
   */
  static async exists(id: string): Promise<boolean> {
    FirePlus.validateInitialization();
    try {
      const instance = new (this as any)();
      const docRef = instance.getDocRef(id);
      const docSnap = await getDoc(docRef);
      return docSnap.exists();
    } catch (error) {
      console.error("Error checking if document exists:", error);
      return false;
    }
  }

  /**
   * Count all documents in the collection
   *
   * @example
   * ```typescript
   * const count = await User.count();
   * console.log(`Total users: ${count}`);
   * ```
   *
   * @returns Promise resolving to the count of documents
   * @throws Error if FirePlus is not initialized
   */
  static async count(): Promise<number> {
    FirePlus.validateInitialization();
    try {
      const instance = new (this as any)();
      const querySnapshot = await getDocs(instance.getCollectionRef());
      return querySnapshot.size;
    } catch (error) {
      console.error("Error counting documents:", error);
      return 0;
    }
  }

  /**
   * Count documents matching specific query constraints
   *
   * @example
   * ```typescript
   * const count = await User.countWhere([
   *   where("age", ">=", 18),
   *   where("city", "==", "New York")
   * ]);
   * console.log(`Users matching criteria: ${count}`);
   * ```
   *
   * @param constraints Array of Firestore query constraints
   * @returns Promise resolving to the count of matching documents
   * @throws Error if FirePlus is not initialized
   */
  static async countWhere(constraints: QueryConstraint[]): Promise<number> {
    FirePlus.validateInitialization();
    try {
      const instance = new (this as any)();
      const q = query(instance.getCollectionRef(), ...constraints);
      const querySnapshot = await getDocs(q);
      return querySnapshot.size;
    } catch (error) {
      console.error("Error counting documents with constraints:", error);
      return 0;
    }
  }

  /**
   * Delete a document by ID
   *
   * @example
   * ```typescript
   * const success = await User.deleteById("existing-id");
   * if (success) {
   *   console.log("Document deleted successfully");
   * }
   * ```
   *
   * @param id Document ID
   * @returns Promise resolving to true if deletion was successful, false otherwise
   * @throws Error if FirePlus is not initialized
   */
  static async deleteById(id: string): Promise<boolean> {
    FirePlus.validateInitialization();
    try {
      const instance = new (this as any)();
      await deleteDoc(instance.getDocRef(id));
      return true;
    } catch (error) {
      console.error("Error deleting document by ID:", error);
      return false;
    }
  }

  /**
   * Update a document by ID
   *
   * @example
   * ```typescript
   * const success = await User.updateById("existing-id", {
   *   name: "John Doe",
   *   age: 30
   * });
   * if (success) {
   *   console.log("Document updated successfully");
   * }
   * ```
   *
   * @param id Document ID
   * @param data Data to update
   * @returns Promise resolving to true if update was successful, false otherwise
   * @throws Error if FirePlus is not initialized
   */
  static async updateById(id: string, data: DocumentData): Promise<boolean> {
    FirePlus.validateInitialization();
    try {
      const instance = new (this as any)();
      data.updatedAt = new Date();
      await updateDoc(instance.getDocRef(id), data);
      return true;
    } catch (error) {
      console.error("Error updating document by ID:", error);
      return false;
    }
  }
}

export default FirePlus;
